version: '3.8'

services:
  gpt-3.5-rest-api:
    image: ernestdecina/gpt-3.5-rest-api
    build: 
      context: ./gpt-3.5-rest-api
    ports:
      - 3000
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gpt-3.5-rest-api
    ports:
      - 3000:4000